export const screenRoutes = [
  { id: 'S-01', path: '/blank', title: 'これからの時間', description: '空いた時間を、あなたの楽しみに変えていく。', next: '/' },
  { id: 'S-02', path: '/', title: '明日が、少し楽しみになる。', description: '小さな「やってみたい」を、未来の予約に。', next: '/wish' },
  { id: 'S-03', path: '/wish', title: 'どんなことをしてみたい？', description: 'まだ曖昧でも大丈夫。今の気持ちから始めましょう。', next: '/questions' },
  { id: 'S-04', path: '/tomorrow', title: '明日を、どんな日にしたい？', description: '外に出る。何か作る。ゆっくり休む。それも一歩です。', next: '/candidates' },
  { id: 'S-05', path: '/candidates', title: 'まず、一度だけ試してみる', description: '好きなことは、試してから見つけても大丈夫。', next: '/questions' },
  { id: 'S-06', path: '/questions', title: 'あなたに合う一歩を探す', description: '使える時間や予算を、無理のない範囲で。', next: '/future' },
  { id: 'S-07', path: '/future', title: '10年後の、好きな日常', description: '続けていたい暮らしと、必要な時間を思い描きます。', next: '/tree' },
  { id: 'S-08', path: '/tree', title: '未来につながる道のり', description: '遠い願いを、今週できることまで小さく。', next: '/schedule' },
  { id: 'S-09', path: '/schedule', title: '最初の一日を決める', description: '自分のための時間を、ひとつ確保しましょう。', next: '/ticket/demo' },
  { id: 'S-10', path: '/ticket/demo', title: 'あなたのリザーブ票', description: 'やりたいことと、最初の一歩を一枚に。', next: '/calendar/demo' },
  { id: 'S-11', path: '/calendar/demo', title: 'カレンダーに入れる', description: 'いつもの予定の中に、あなたの楽しみを。', next: '/home' },
  { id: 'S-12', path: '/home', title: '次の楽しみ', description: 'できた日も、できなかった日も。ここからまた。', next: '/reflect/demo' },
  { id: 'S-13', path: '/reflect/demo', title: 'やってみて、どうでしたか？', description: '結果だけでなく、あなたの気持ちも残しましょう。', next: '/next-step/demo' },
  { id: 'S-14', path: '/next-step/demo', title: '次は、どんな一歩にする？', description: '小さくする、休む、別のことを試す。あなたのペースで。', next: '/schedule' },
  { id: 'S-15', path: '/next-week', title: '来週の楽しみをつくる', description: '楽しかったことを、次の予定へつなげましょう。', next: '/schedule' },
  { id: 'S-16', path: '/history', title: 'これまでの一歩', description: '試したことも、気づいたことも、あなたの記録です。', next: '/home' },
  { id: 'S-17', path: '/settings', title: '設定', description: 'この端末の記録と、デモの表示を確認できます。', next: '/home' },
  { id: 'S-18', path: '/support', title: 'ひと息つく時間', description: '今日は進まなくても大丈夫です。', next: '/home' },
  { id: 'S-19', path: '/survey', title: '使ってみて、どうでしたか？', description: '明日、少しやってみたいと思えましたか。', next: '/home' },
  { id: 'G-01', path: '/concept/records', title: '記録から、好きに気づく', description: '自分でも気づかなかった興味を見つける未来。', next: '/questions' },
  { id: 'G-02', path: '/concept/auto', title: '記録が、そっとつながる', description: 'あなたの確認を受けて、体験を記録する未来。', next: '/home' },
  { id: 'G-03', path: '/concept/paths', title: '誰かの一歩が、ヒントになる', description: '似た出発点の人の体験から、次の一歩を探す未来。', next: '/home' },
] as const;
export type ScreenId = typeof screenRoutes[number]['id'];
